### ISSUE TITLE
iOS platform not working

### ISSUE THREAD

**Issue by Ahmedlag** [CodifiLLC/cordova-plugin-embedded-barcode-reader#1]
Hello,

Thank you so much for this useful plugin & the efforts !

Idk if this project is still maintained, i just wanted to know if there is a way you can update the iOS swift code, apparently it's not functional :(

I'm using XCODE 11.4.1 , and when the app builds, XCODE comes up with some errors : 
![image](https://user-images.githubusercontent.com/22698453/82478256-f1461b00-9ad0-11ea-96ea-0578e12f544b.png)

I apply all the fixes XCODE proposes, but when i do **EmbeddedBarcodeReader.startCamera(options)** on my Iphone XS max (13.4.1) it shows only camera feed with no hud or scan callblack

In the XCODE console, i get these errors : 

ERROR: Method 'startListening:' not defined in Plugin 'EmbeddedBarcodeReader'
FAILED pluginJSON =["EmbeddedBarcodeReader211085211","EmbeddedBarcodeReader","startListening",[]]
ERROR: Method 'startReading:' not defined in Plugin 'EmbeddedBarcodeReader'
FAILED pluginJSON = ["INVALID","EmbeddedBarcodeReader","startReading",[0,0,414,756,"back",true,false,true,1]]

Swift Compiler : 4

Can you please help ?

**Comment by matthewdickinson** [comment]
I'll see if we can resolve that. I can't promise that it will be immediately, but I'll do my best.

**Comment by Ahmedlag** [comment]
@matthewdickinson thank you so much sir, your quick response gave me huge boost of hope to see this working 
Thank you again 👍 ❤️

**Comment by Ahmedlag** [comment]
Hello @matthewdickinson, any update about this issue ?
Thank you

**Comment by matthewdickinson** [comment]
@Ahmedlag I'm sorry for the huge delay. We just pushed an update that _should_ fix it. We'll be verifying this today, but if you want to try it now, you can give it a shot.

**Comment by Ahmedlag** [comment]
Hello @matthewdickinson , thank you guys so much, i'll give it a try today and keep you up !
Thank you again for your precious time

**Comment by dwimarufalvansuri** [comment]
hai @matthewdickinson and @ahmedlag  , i can fix that error using this code :

sample :

> _**@objc(startReading:)**
> func startReading(_ command: CDVInvokedUrlCommand) {_
> 

reference : https://stackoverflow.com/a/50257501


but in my iOS project, i still cannot show camera preview.

my script :
           

> var optionsQRScanner = {
>                 x: 0,
>                 y: 0,
>                 width: window.screen.width,
>                 height: window.screen.height,
>                 camera: EmbeddedBarcodeReader.CAMERA_DIRECTION.BACK,
>                 toBack: false
> };
> EmbeddedBarcodeReader.startCamera(optionsQRScanner, function (success) {
>                 console.log("QRScanner start success: " + JSON.stringify(success));
> }, function (error) {
>                 console.log("QRScanner start err: " + JSON.stringify(error));
> });

i got log "QRScanner start success:" but camera preview not showing up.
is there any suggestion?

Thank you for your time. :D
<img width="452" alt="Screen Shot 2020-08-23 at 03 02 37" src="https://user-images.githubusercontent.com/2959401/90964720-69b3e200-e4ed-11ea-8a17-2656b15db97e.png">

**Comment by matthewdickinson** [comment]
@Ahmedlag @dwimarufalvansuri Again, I apologize for the delay on this. We just pushed updates last night that should make this work. Can you please test it again?

**Comment by dwimarufalvansuri** [comment]
hai @matthewdickinson , thanks for your response. :)
anw, i still cannot showing up camera preview, which version xcode are you using?
i use xcode version 11.6 and test using iphone X (13.6.1).
or maybe, can you attach your cordova project demo?

many thanks. :)

**Comment by ReubenRubio3** [comment]
@dwimarufalvansuri Here is a test app (built with Ionic) that uses the plugin. iOS adds a black background at the root of the app that needs to be changed to transparent for the camera preview to show. (You'll need to `npm install` and `ionic cordova platform add ios` before building the project for ios).
[test-app.zip](https://github.com/CodifiLLC/cordova-plugin-embedded-barcode-reader/files/5158840/test-app.zip)
